/**
 * Signals Module
 *
 * Manages advisor action signals - the items that populate the advisor action queue.
 * Signals are generated by:
 * - Signal rules (automated)
 * - Manual creation by advisors
 * - System events (deadlines, milestones)
 *
 * Supports:
 * - Signal CRUD operations
 * - Advisor queue queries (prioritized, filtered)
 * - Signal resolution and status tracking
 * - Student signal history
 *
 * Authorization:
 * - University admins can view all signals for their university
 * - Advisors can view signals for their assigned students
 * - Students can view their own signals (limited fields)
 */

import { v } from 'convex/values';

import { internal } from './_generated/api';
import { Id } from './_generated/dataModel';
import { internalMutation, mutation, query, QueryCtx } from './_generated/server';
import { getCurrentUser, requireTenant } from './advisor_auth';
import { safeLogAudit } from './lib/auditLogger';
import { requireAdvisor } from './lib/authorization';
import { assertUniversityAccess, requireUniversityAdmin } from './lib/roles';

// ============================================================================
// VALIDATORS
// ============================================================================

const signalTypeValidator = v.union(
  v.literal('needs_outreach'),
  v.literal('application_support'),
  v.literal('document_review'),
  v.literal('milestone_check'),
  v.literal('custom'),
);

const priorityValidator = v.union(
  v.literal('low'),
  v.literal('medium'),
  v.literal('high'),
  v.literal('urgent'),
);

const statusValidator = v.union(
  v.literal('active'),
  v.literal('snoozed'),
  v.literal('resolved'),
  v.literal('dismissed'),
  v.literal('archived'), // Soft-deleted to preserve metrics/audit history
);

const sourceValidator = v.union(v.literal('rule'), v.literal('manual'), v.literal('system'));

const resolutionTypeValidator = v.union(
  v.literal('action_taken'),
  v.literal('no_action_needed'),
  v.literal('dismissed'),
  v.literal('auto_resolved'),
);

const relatedTypeValidator = v.union(
  v.literal('application'),
  v.literal('goal'),
  v.literal('resume'),
  v.literal('session'),
);

// ============================================================================
// ROLE-SCOPED ACCESS HELPERS
// ============================================================================

/**
 * Get the set of student IDs that the current user can access signals for.
 * Returns null if user has full access (super_admin, university_admin).
 *
 * - super_admin / university_admin: full access to university signals
 * - advisor: only signals for assigned students (via student_advisors)
 * - student: only their own signals
 */
async function getAllowedStudentIds(
  ctx: QueryCtx,
  sessionCtx: { role: string; userId: Id<'users'> },
  universityId: Id<'universities'>,
): Promise<Set<Id<'users'>> | null> {
  // Super admin and university admin have full access
  if (sessionCtx.role === 'super_admin' || sessionCtx.role === 'university_admin') {
    return null; // null means full access
  }

  // Advisors can only access signals for their assigned students
  if (sessionCtx.role === 'advisor') {
    const assignments = await ctx.db
      .query('student_advisors')
      .withIndex('by_advisor', (q) => q.eq('advisor_id', sessionCtx.userId))
      .filter((q) => q.eq(q.field('university_id'), universityId))
      .collect();
    return new Set(assignments.map((a) => a.student_id));
  }

  // Students can only access their own signals
  if (sessionCtx.role === 'student') {
    return new Set([sessionCtx.userId]);
  }

  // Any other role: no access
  return new Set();
}

/**
 * Check if the current user can access a specific student's signals.
 * Throws an error if access is denied.
 */
async function assertSignalAccessForStudent(
  ctx: QueryCtx,
  sessionCtx: { role: string; userId: Id<'users'> },
  universityId: Id<'universities'>,
  studentId: Id<'users'>,
): Promise<void> {
  const allowedIds = await getAllowedStudentIds(ctx, sessionCtx, universityId);

  // null means full access
  if (allowedIds === null) return;

  if (!allowedIds.has(studentId)) {
    throw new Error('Unauthorized: Cannot access signals for this student');
  }
}

// ============================================================================
// QUEUE QUERIES (Advisor Action Queue)
// ============================================================================

/**
 * Get the advisor action queue - signals prioritized for action.
 * This is the main query for the advisor queue UI.
 *
 * OPTIMIZATION NOTES:
 * - Full-access users (super_admin, university_admin): Use paginate() with index
 * - Scoped users (advisors): Must use collect() + filter due to role-based filtering
 *   that can't be pushed to an index. For very large universities, consider
 *   denormalizing advisor_id onto signals for index-based filtering.
 */
export const getAdvisorQueue = query({
  args: {
    universityId: v.id('universities'),
    status: v.optional(statusValidator),
    signalType: v.optional(signalTypeValidator),
    priority: v.optional(priorityValidator),
    studentId: v.optional(v.id('users')),
    limit: v.optional(v.number()),
    cursor: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    const sessionCtx = await getCurrentUser(ctx);
    const limit = args.limit ?? 50;
    const status = args.status ?? 'active';

    // Authorization check - university membership
    if (sessionCtx.role !== 'super_admin') {
      const universityId = requireTenant(sessionCtx);
      if (universityId !== args.universityId) {
        throw new Error('Unauthorized: Cannot access signals for another university');
      }
    }

    // Role-scoped access - get allowed student IDs for this user
    const allowedStudentIds = await getAllowedStudentIds(ctx, sessionCtx, args.universityId);

    // If requesting a specific student, verify access
    if (args.studentId && allowedStudentIds !== null && !allowedStudentIds.has(args.studentId)) {
      throw new Error('Unauthorized: Cannot access signals for this student');
    }

    // OPTIMIZED PATH: For specific student queries, use student index
    if (args.studentId) {
      const signals = await ctx.db
        .query('signals')
        .withIndex('by_student_status', (q) =>
          q.eq('student_id', args.studentId!).eq('status', status),
        )
        .order('desc') // Most recent first
        .collect();

      // Apply additional filters in-memory (small result set per student)
      let filtered = signals.filter((s) => s.university_id === args.universityId);
      if (args.signalType) {
        filtered = filtered.filter((s) => s.signal_type === args.signalType);
      }
      if (args.priority) {
        filtered = filtered.filter((s) => s.priority === args.priority);
      }

      // Sort by priority then triggered_at
      const priorityOrder = { urgent: 0, high: 1, medium: 2, low: 3 };
      filtered.sort((a, b) => {
        const priorityDiff = priorityOrder[a.priority] - priorityOrder[b.priority];
        if (priorityDiff !== 0) return priorityDiff;
        return a.triggered_at - b.triggered_at;
      });

      const total = filtered.length;
      const startIndex = args.cursor ? parseInt(args.cursor, 10) : 0;
      const page = filtered.slice(startIndex, startIndex + limit);
      const nextCursor = startIndex + limit < total ? String(startIndex + limit) : null;

      // Enrich with student info (single student, efficient)
      const student = await ctx.db.get(args.studentId);
      const enrichedSignals = page.map((signal) => ({
        ...signal,
        student: student
          ? {
              id: student._id,
              name: student.name,
              email: student.email,
              profileImage: student.profile_image,
            }
          : null,
      }));

      return {
        signals: enrichedSignals,
        total,
        cursor: nextCursor,
        hasMore: nextCursor !== null,
      };
    }

    // OPTIMIZED PATH: Full-access users can use index-based pagination
    const hasFullAccess = allowedStudentIds === null;

    if (hasFullAccess && !args.signalType) {
      // Use priority index for better ordering if filtering by priority
      if (args.priority) {
        const signals = await ctx.db
          .query('signals')
          .withIndex('by_university_priority', (q) =>
            q
              .eq('university_id', args.universityId)
              .eq('status', status)
              .eq('priority', args.priority!),
          )
          .order('asc') // Oldest first within priority
          .collect();

        const total = signals.length;
        const startIndex = args.cursor ? parseInt(args.cursor, 10) : 0;
        const page = signals.slice(startIndex, startIndex + limit);
        const nextCursor = startIndex + limit < total ? String(startIndex + limit) : null;

        // Batch fetch student info
        const studentIds = [...new Set(page.map((s) => s.student_id))];
        const students = await Promise.all(studentIds.map((id) => ctx.db.get(id)));
        const studentMap = new Map(students.filter(Boolean).map((s) => [s!._id, s!]));

        const enrichedSignals = page.map((signal) => {
          const student = studentMap.get(signal.student_id);
          return {
            ...signal,
            student: student
              ? {
                  id: student._id,
                  name: student.name,
                  email: student.email,
                  profileImage: student.profile_image,
                }
              : null,
          };
        });

        return {
          signals: enrichedSignals,
          total,
          cursor: nextCursor,
          hasMore: nextCursor !== null,
        };
      }

      // No priority filter - use time-ordered index for consistent pagination
      const signals = await ctx.db
        .query('signals')
        .withIndex('by_university_status_triggered', (q) =>
          q.eq('university_id', args.universityId).eq('status', status),
        )
        .order('asc') // Oldest first
        .collect();

      // Sort by priority then triggered_at (in-memory, but already time-ordered)
      const priorityOrder = { urgent: 0, high: 1, medium: 2, low: 3 };
      signals.sort((a, b) => {
        const priorityDiff = priorityOrder[a.priority] - priorityOrder[b.priority];
        if (priorityDiff !== 0) return priorityDiff;
        return a.triggered_at - b.triggered_at;
      });

      const total = signals.length;
      const startIndex = args.cursor ? parseInt(args.cursor, 10) : 0;
      const page = signals.slice(startIndex, startIndex + limit);
      const nextCursor = startIndex + limit < total ? String(startIndex + limit) : null;

      // Batch fetch student info
      const studentIds = [...new Set(page.map((s) => s.student_id))];
      const students = await Promise.all(studentIds.map((id) => ctx.db.get(id)));
      const studentMap = new Map(students.filter(Boolean).map((s) => [s!._id, s!]));

      const enrichedSignals = page.map((signal) => {
        const student = studentMap.get(signal.student_id);
        return {
          ...signal,
          student: student
            ? {
                id: student._id,
                name: student.name,
                email: student.email,
                profileImage: student.profile_image,
              }
            : null,
        };
      });

      return {
        signals: enrichedSignals,
        total,
        cursor: nextCursor,
        hasMore: nextCursor !== null,
      };
    }

    // SCOPED ACCESS PATH: Advisors need post-query filtering
    // NOTE: For very large universities, this could be optimized by denormalizing
    // advisor_id onto signals to enable index-based filtering
    const allSignals = await ctx.db
      .query('signals')
      .withIndex('by_university_status_triggered', (q) =>
        q.eq('university_id', args.universityId).eq('status', status),
      )
      .order('asc')
      .collect();

    // Apply role-scoped filtering
    let filtered = allSignals.filter((s) => allowedStudentIds!.has(s.student_id));

    // Apply additional filters
    if (args.signalType) {
      filtered = filtered.filter((s) => s.signal_type === args.signalType);
    }
    if (args.priority) {
      filtered = filtered.filter((s) => s.priority === args.priority);
    }

    // Sort by priority (urgent first), then by triggered_at (oldest first)
    const priorityOrder = { urgent: 0, high: 1, medium: 2, low: 3 };
    filtered.sort((a, b) => {
      const priorityDiff = priorityOrder[a.priority] - priorityOrder[b.priority];
      if (priorityDiff !== 0) return priorityDiff;
      return a.triggered_at - b.triggered_at;
    });

    // Apply pagination
    const total = filtered.length;
    const startIndex = args.cursor ? parseInt(args.cursor, 10) : 0;
    const page = filtered.slice(startIndex, startIndex + limit);
    const nextCursor = startIndex + limit < total ? String(startIndex + limit) : null;

    // Batch fetch student info (more efficient than per-signal)
    const studentIds = [...new Set(page.map((s) => s.student_id))];
    const students = await Promise.all(studentIds.map((id) => ctx.db.get(id)));
    const studentMap = new Map(students.filter(Boolean).map((s) => [s!._id, s!]));

    const enrichedSignals = page.map((signal) => {
      const student = studentMap.get(signal.student_id);
      return {
        ...signal,
        student: student
          ? {
              id: student._id,
              name: student.name,
              email: student.email,
              profileImage: student.profile_image,
            }
          : null,
      };
    });

    return {
      signals: enrichedSignals,
      total,
      cursor: nextCursor,
      hasMore: nextCursor !== null,
    };
  },
});

/**
 * Get queue summary stats for the advisor dashboard.
 */
export const getQueueStats = query({
  args: {
    universityId: v.id('universities'),
  },
  handler: async (ctx, args) => {
    const sessionCtx = await getCurrentUser(ctx);

    // Role check: Only advisors and admins can access queue stats
    const allowedRoles = ['super_admin', 'university_admin', 'advisor'];
    if (!allowedRoles.includes(sessionCtx.role)) {
      throw new Error('Unauthorized: Advisor or admin access required');
    }

    // Tenant check: Non-super-admins can only access their own university
    if (sessionCtx.role !== 'super_admin') {
      const universityId = requireTenant(sessionCtx);
      if (universityId !== args.universityId) {
        throw new Error('Unauthorized: Cannot access signals for another university');
      }
    }

    // Get all active signals
    const activeSignals = await ctx.db
      .query('signals')
      .withIndex('by_university_status', (q) =>
        q.eq('university_id', args.universityId).eq('status', 'active'),
      )
      .collect();

    // Calculate stats
    const byPriority = {
      urgent: 0,
      high: 0,
      medium: 0,
      low: 0,
    };

    const byType = {
      needs_outreach: 0,
      application_support: 0,
      document_review: 0,
      milestone_check: 0,
      custom: 0,
    };

    for (const signal of activeSignals) {
      byPriority[signal.priority]++;
      byType[signal.signal_type]++;
    }

    // Get snoozed count
    const snoozedSignals = await ctx.db
      .query('signals')
      .withIndex('by_university_status', (q) =>
        q.eq('university_id', args.universityId).eq('status', 'snoozed'),
      )
      .collect();

    // Count due (snooze expired)
    const now = Date.now();
    const dueFromSnooze = snoozedSignals.filter(
      (s) => s.snoozed_until && s.snoozed_until <= now,
    ).length;

    return {
      total: activeSignals.length,
      byPriority,
      byType,
      snoozed: snoozedSignals.length,
      dueFromSnooze,
    };
  },
});

// ============================================================================
// SIGNAL QUERIES
// ============================================================================

/**
 * Get a single signal by ID.
 */
export const getSignal = query({
  args: {
    signalId: v.id('signals'),
  },
  handler: async (ctx, args) => {
    const sessionCtx = await getCurrentUser(ctx);

    const signal = await ctx.db.get(args.signalId);
    if (!signal) {
      throw new Error('Signal not found');
    }

    // Authorization check - university membership
    if (sessionCtx.role !== 'super_admin') {
      const universityId = requireTenant(sessionCtx);
      if (signal.university_id !== universityId) {
        throw new Error('Unauthorized: Signal is not in your university');
      }
    }

    // Role-scoped access - verify user can access this student's signals
    await assertSignalAccessForStudent(ctx, sessionCtx, signal.university_id, signal.student_id);

    // Enrich with student and rule info
    const student = await ctx.db.get(signal.student_id);
    const rule = signal.rule_id ? await ctx.db.get(signal.rule_id) : null;

    return {
      ...signal,
      student: student
        ? {
            id: student._id,
            name: student.name,
            email: student.email,
            profileImage: student.profile_image,
          }
        : null,
      rule: rule
        ? {
            id: rule._id,
            name: rule.name,
          }
        : null,
    };
  },
});

/**
 * Get signals for a specific student.
 */
export const getSignalsByStudent = query({
  args: {
    studentId: v.id('users'),
    status: v.optional(statusValidator),
    limit: v.optional(v.number()),
  },
  handler: async (ctx, args) => {
    const sessionCtx = await getCurrentUser(ctx);
    const limit = args.limit ?? 20;

    const student = await ctx.db.get(args.studentId);
    if (!student) {
      throw new Error('Student not found');
    }

    // Authorization check - advisors must also be in the same university
    if (sessionCtx.role !== 'super_admin') {
      const universityId = requireTenant(sessionCtx);
      if (student.university_id !== universityId) {
        throw new Error('Unauthorized: Cannot access signals for another university');
      }
    }

    // Verify student has a university association
    if (!student.university_id) {
      throw new Error('Student is not associated with a university');
    }

    // Role-scoped access - advisors can only access signals for their assigned students
    await assertSignalAccessForStudent(ctx, sessionCtx, student.university_id, student._id);

    let query;
    if (args.status) {
      query = ctx.db
        .query('signals')
        .withIndex('by_student_status', (q) =>
          q.eq('student_id', args.studentId).eq('status', args.status!),
        );
    } else {
      query = ctx.db
        .query('signals')
        .withIndex('by_student', (q) => q.eq('student_id', args.studentId));
    }

    const signals = await query.order('desc').take(limit);

    return signals;
  },
});

// ============================================================================
// SIGNAL MUTATIONS
// ============================================================================

/**
 * Create a signal manually.
 * Used by advisors to create ad-hoc signals.
 */
export const createSignal = mutation({
  args: {
    universityId: v.id('universities'),
    studentId: v.id('users'),
    signalType: signalTypeValidator,
    title: v.string(),
    description: v.optional(v.string()),
    priority: priorityValidator,
    relatedType: v.optional(relatedTypeValidator),
    relatedId: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    // Allow advisors, university_admins, and super_admins to create signals
    const user = await requireAdvisor(ctx);
    assertUniversityAccess(user, args.universityId);

    // Verify student exists and is in the university
    const student = await ctx.db.get(args.studentId);
    if (!student) {
      throw new Error('Student not found');
    }
    if (student.university_id !== args.universityId) {
      throw new Error('Student is not in this university');
    }

    const now = Date.now();

    const signalId = await ctx.db.insert('signals', {
      university_id: args.universityId,
      student_id: args.studentId,
      source: 'manual',
      signal_type: args.signalType,
      title: args.title,
      description: args.description,
      priority: args.priority,
      related_type: args.relatedType,
      related_id: args.relatedId,
      status: 'active',
      triggered_at: now,
      created_at: now,
      updated_at: now,
    });

    // Audit log: signal created
    await safeLogAudit(ctx, {
      category: 'user_action',
      action: 'signal.created',
      actorUserId: user._id,
      actorRole: user.role,
      actorUniversityId: args.universityId,
      targetType: 'signal',
      targetId: signalId,
      metadata: {
        studentId: args.studentId,
        studentName: student.name,
        signalType: args.signalType,
        title: args.title,
        priority: args.priority,
      },
    });

    // Trigger in-app notifications for advisors
    await ctx.scheduler.runAfter(0, internal.signal_notifications.notifyAdvisorsForSignal, {
      signalId,
      studentId: args.studentId,
      universityId: args.universityId,
      priority: args.priority,
      signalTitle: args.title,
      signalDescription: args.description,
    });

    return signalId;
  },
});

/**
 * Create a signal from a rule (internal use).
 * Called by the signal evaluation system.
 */
export const createSignalFromRule = internalMutation({
  args: {
    ruleId: v.id('signal_rules'),
    studentId: v.id('users'),
    contextSnapshot: v.optional(v.any()),
  },
  handler: async (ctx, args) => {
    // Get the rule
    const rule = await ctx.db.get(args.ruleId);
    if (!rule) {
      throw new Error('Signal rule not found');
    }

    // Check cooldown - don't create if similar signal exists recently
    if (rule.cooldown_days) {
      const cooldownMs = rule.cooldown_days * 24 * 60 * 60 * 1000;
      const cooldownStart = Date.now() - cooldownMs;

      const recentSignal = await ctx.db
        .query('signals')
        .withIndex('by_rule', (q) => q.eq('rule_id', args.ruleId))
        .filter((q) =>
          q.and(
            q.eq(q.field('student_id'), args.studentId),
            q.gte(q.field('triggered_at'), cooldownStart),
          ),
        )
        .first();

      if (recentSignal) {
        // Skip - still in cooldown
        return null;
      }
    }

    const now = Date.now();

    const signalId = await ctx.db.insert('signals', {
      university_id: rule.university_id,
      student_id: args.studentId,
      rule_id: args.ruleId,
      source: 'rule',
      signal_type: rule.signal_type,
      title: rule.name,
      description: rule.description,
      priority: rule.priority,
      context_snapshot: args.contextSnapshot,
      status: 'active',
      triggered_at: now,
      created_at: now,
      updated_at: now,
    });

    // Auto-create follow-up if configured
    if (rule.auto_create_followup) {
      // Create follow-up using internal mutation
      const followupId = await ctx.scheduler.runAfter(
        0,
        internal.followups.createFollowupFromSignal,
        {
          signalId,
          studentId: args.studentId,
          universityId: rule.university_id,
          title: rule.followup_template || `Action needed: ${rule.name}`,
          description: rule.description,
          priority: rule.priority,
          dueInDays: 7, // Default 7 days to act on the signal
        },
      );

      // Link follow-up back to signal (fire-and-forget, will be linked via engagement_signal_id)
    }

    return signalId;
  },
});

/**
 * Resolve a signal.
 */
export const resolveSignal = mutation({
  args: {
    signalId: v.id('signals'),
    resolutionType: resolutionTypeValidator,
    resolutionNotes: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    const sessionCtx = await getCurrentUser(ctx);

    // Students cannot resolve signals
    if (sessionCtx.role === 'student') {
      throw new Error('Unauthorized: Students cannot resolve signals');
    }

    const signal = await ctx.db.get(args.signalId);
    if (!signal) {
      throw new Error('Signal not found');
    }

    // Authorization check - university membership
    if (sessionCtx.role !== 'super_admin') {
      const universityId = requireTenant(sessionCtx);
      if (signal.university_id !== universityId) {
        throw new Error('Unauthorized: Signal is not in your university');
      }
    }

    // Role-scoped access - advisors can only resolve signals for their assigned students
    await assertSignalAccessForStudent(ctx, sessionCtx, signal.university_id, signal.student_id);

    const now = Date.now();

    await ctx.db.patch(args.signalId, {
      status: 'resolved',
      resolved_at: now,
      resolved_by: sessionCtx.userId,
      resolution_type: args.resolutionType,
      resolution_notes: args.resolutionNotes,
      updated_at: now,
    });

    // Audit log: signal resolved
    await safeLogAudit(ctx, {
      category: 'user_action',
      action: 'signal.resolved',
      actorUserId: sessionCtx.userId,
      actorRole: sessionCtx.role,
      actorUniversityId: signal.university_id,
      targetType: 'signal',
      targetId: args.signalId,
      previousValue: { status: signal.status },
      newValue: { status: 'resolved', resolutionType: args.resolutionType },
      metadata: {
        studentId: signal.student_id,
        signalType: signal.signal_type,
        title: signal.title,
        resolutionNotes: args.resolutionNotes,
      },
    });

    return args.signalId;
  },
});

/**
 * Dismiss a signal (mark as not actionable).
 */
export const dismissSignal = mutation({
  args: {
    signalId: v.id('signals'),
    reason: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    const sessionCtx = await getCurrentUser(ctx);

    // Students cannot dismiss signals
    if (sessionCtx.role === 'student') {
      throw new Error('Unauthorized: Students cannot dismiss signals');
    }

    const signal = await ctx.db.get(args.signalId);
    if (!signal) {
      throw new Error('Signal not found');
    }

    // Authorization check - university membership
    if (sessionCtx.role !== 'super_admin') {
      const universityId = requireTenant(sessionCtx);
      if (signal.university_id !== universityId) {
        throw new Error('Unauthorized: Signal is not in your university');
      }
    }

    // Role-scoped access - advisors can only dismiss signals for their assigned students
    await assertSignalAccessForStudent(ctx, sessionCtx, signal.university_id, signal.student_id);

    const now = Date.now();

    await ctx.db.patch(args.signalId, {
      status: 'dismissed',
      resolved_at: now,
      resolved_by: sessionCtx.userId,
      resolution_type: 'dismissed',
      resolution_notes: args.reason,
      updated_at: now,
    });

    // Audit log: signal dismissed
    await safeLogAudit(ctx, {
      category: 'user_action',
      action: 'signal.dismissed',
      actorUserId: sessionCtx.userId,
      actorRole: sessionCtx.role,
      actorUniversityId: signal.university_id,
      targetType: 'signal',
      targetId: args.signalId,
      previousValue: { status: signal.status },
      newValue: { status: 'dismissed' },
      metadata: {
        studentId: signal.student_id,
        signalType: signal.signal_type,
        title: signal.title,
        dismissReason: args.reason,
      },
    });

    return args.signalId;
  },
});

/**
 * Snooze a signal for later.
 */
export const snoozeSignal = mutation({
  args: {
    signalId: v.id('signals'),
    snoozeDays: v.number(),
  },
  handler: async (ctx, args) => {
    const sessionCtx = await getCurrentUser(ctx);

    // Students cannot snooze signals
    if (sessionCtx.role === 'student') {
      throw new Error('Unauthorized: Students cannot snooze signals');
    }

    if (args.snoozeDays <= 0 || args.snoozeDays > 30) {
      throw new Error('Snooze duration must be between 1 and 30 days');
    }

    const signal = await ctx.db.get(args.signalId);
    if (!signal) {
      throw new Error('Signal not found');
    }

    // Authorization check - university membership
    if (sessionCtx.role !== 'super_admin') {
      const universityId = requireTenant(sessionCtx);
      if (signal.university_id !== universityId) {
        throw new Error('Unauthorized: Signal is not in your university');
      }
    }

    // Role-scoped access - advisors can only snooze signals for their assigned students
    await assertSignalAccessForStudent(ctx, sessionCtx, signal.university_id, signal.student_id);

    const now = Date.now();
    const snoozedUntil = now + args.snoozeDays * 24 * 60 * 60 * 1000;

    await ctx.db.patch(args.signalId, {
      status: 'snoozed',
      snoozed_until: snoozedUntil,
      updated_at: now,
    });

    // Audit log: signal snoozed
    await safeLogAudit(ctx, {
      category: 'user_action',
      action: 'signal.snoozed',
      actorUserId: sessionCtx.userId,
      actorRole: sessionCtx.role,
      actorUniversityId: signal.university_id,
      targetType: 'signal',
      targetId: args.signalId,
      previousValue: { status: signal.status },
      newValue: { status: 'snoozed', snoozedUntil, snoozeDays: args.snoozeDays },
      metadata: {
        studentId: signal.student_id,
        signalType: signal.signal_type,
        title: signal.title,
      },
    });

    return { signalId: args.signalId, snoozedUntil };
  },
});

/**
 * Unsnooze a signal (make it active again).
 */
export const unsnoozeSignal = mutation({
  args: {
    signalId: v.id('signals'),
  },
  handler: async (ctx, args) => {
    const sessionCtx = await getCurrentUser(ctx);

    // Students cannot unsnooze signals
    if (sessionCtx.role === 'student') {
      throw new Error('Unauthorized: Students cannot unsnooze signals');
    }

    const signal = await ctx.db.get(args.signalId);
    if (!signal) {
      throw new Error('Signal not found');
    }

    if (signal.status !== 'snoozed') {
      throw new Error('Signal is not snoozed');
    }

    // Authorization check - university membership
    if (sessionCtx.role !== 'super_admin') {
      const universityId = requireTenant(sessionCtx);
      if (signal.university_id !== universityId) {
        throw new Error('Unauthorized: Signal is not in your university');
      }
    }

    // Role-scoped access - advisors can only unsnooze signals for their assigned students
    await assertSignalAccessForStudent(ctx, sessionCtx, signal.university_id, signal.student_id);

    await ctx.db.patch(args.signalId, {
      status: 'active',
      snoozed_until: undefined,
      updated_at: Date.now(),
    });

    return args.signalId;
  },
});

/**
 * Bulk resolve signals.
 */
export const bulkResolveSignals = mutation({
  args: {
    signalIds: v.array(v.id('signals')),
    resolutionType: resolutionTypeValidator,
    resolutionNotes: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    const sessionCtx = await getCurrentUser(ctx);

    // Students cannot resolve signals
    if (sessionCtx.role === 'student') {
      throw new Error('Unauthorized: Students cannot resolve signals');
    }

    if (args.signalIds.length === 0) {
      return { resolved: 0 };
    }

    if (args.signalIds.length > 50) {
      throw new Error('Cannot bulk resolve more than 50 signals at once');
    }

    // Pre-compute allowed student IDs for advisors (avoids repeated DB queries)
    let allowedStudentIds: Set<Id<'users'>> | null = null;
    if (sessionCtx.role === 'advisor') {
      const universityId = requireTenant(sessionCtx);
      const assignments = await ctx.db
        .query('student_advisors')
        .withIndex('by_advisor', (q) => q.eq('advisor_id', sessionCtx.userId))
        .filter((q) => q.eq(q.field('university_id'), universityId))
        .collect();
      allowedStudentIds = new Set(assignments.map((a) => a.student_id));
    }

    const now = Date.now();
    let resolved = 0;

    for (const signalId of args.signalIds) {
      const signal = await ctx.db.get(signalId);
      if (!signal) continue;

      // Authorization check - university membership
      if (sessionCtx.role !== 'super_admin') {
        const universityId = requireTenant(sessionCtx);
        if (signal.university_id !== universityId) continue;
      }

      // Role-scoped access - advisors can only resolve signals for their assigned students
      if (allowedStudentIds !== null && !allowedStudentIds.has(signal.student_id)) {
        continue; // Skip signals for unassigned students
      }

      await ctx.db.patch(signalId, {
        status: 'resolved',
        resolved_at: now,
        resolved_by: sessionCtx.userId,
        resolution_type: args.resolutionType,
        resolution_notes: args.resolutionNotes,
        updated_at: now,
      });

      resolved++;
    }

    return { resolved };
  },
});

/**
 * Archive a signal (soft-delete, admin only).
 * Preserves signal data for metrics and audit history.
 */
export const deleteSignal = mutation({
  args: {
    signalId: v.id('signals'),
  },
  handler: async (ctx, args) => {
    const user = await requireUniversityAdmin(ctx);

    const signal = await ctx.db.get(args.signalId);
    if (!signal) {
      throw new Error('Signal not found');
    }

    assertUniversityAccess(user, signal.university_id);

    const now = Date.now();

    // Soft-delete: archive instead of hard delete to preserve metrics/audit history
    await ctx.db.patch(args.signalId, {
      status: 'archived',
      archived_at: now,
      updated_at: now,
    });

    // Audit log: signal archived
    await safeLogAudit(ctx, {
      category: 'user_action',
      action: 'signal.archived',
      actorUserId: user._id,
      actorRole: user.role,
      actorUniversityId: signal.university_id,
      targetType: 'signal',
      targetId: args.signalId,
      previousValue: { status: signal.status },
      newValue: { status: 'archived' },
      metadata: {
        studentId: signal.student_id,
        signalType: signal.signal_type,
        title: signal.title,
      },
    });

    return args.signalId;
  },
});

// ============================================================================
// INTERNAL MUTATIONS (Cron Jobs)
// ============================================================================

/**
 * Reactivate snoozed signals whose snooze period has expired.
 * Called by cron job hourly.
 */
export const unsnoozeDueSignals = internalMutation({
  args: {},
  handler: async (ctx) => {
    const now = Date.now();
    let reactivated = 0;

    // Get all universities with active signal rules (to limit scope)
    const universities = await ctx.db.query('universities').collect();

    for (const university of universities) {
      // Get snoozed signals for this university
      const snoozedSignals = await ctx.db
        .query('signals')
        .withIndex('by_university_status', (q) =>
          q.eq('university_id', university._id).eq('status', 'snoozed'),
        )
        .collect();

      // Reactivate signals where snooze has expired
      for (const signal of snoozedSignals) {
        if (signal.snoozed_until && signal.snoozed_until <= now) {
          await ctx.db.patch(signal._id, {
            status: 'active',
            snoozed_until: undefined,
            updated_at: now,
          });
          reactivated++;
        }
      }
    }

    console.log(`[Signal Cron] Reactivated ${reactivated} snoozed signals`);
    return { reactivated };
  },
});

/**
 * Evaluate all active signal rules and create signals for matching students.
 * Called by cron job (e.g., every 30 minutes or hourly).
 */
export const evaluateSignalRules = internalMutation({
  args: {
    universityId: v.optional(v.id('universities')),
  },
  handler: async (ctx, args) => {
    // Check feature flag - if not enabled, skip evaluation
    const autoEvaluateFlag = await ctx.db
      .query('platform_settings')
      .withIndex('by_setting_key', (q) => q.eq('setting_key', 'advisor.signals.auto_evaluate'))
      .unique();

    if (!autoEvaluateFlag || autoEvaluateFlag.setting_value !== true) {
      console.log('[Signal Cron] Auto-evaluate feature flag is disabled, skipping evaluation');
      return { signalsCreated: 0, rulesEvaluated: 0, studentsChecked: 0, skipped: true };
    }

    const now = Date.now();
    let signalsCreated = 0;
    let rulesEvaluated = 0;
    let studentsChecked = 0;

    // Get universities to process
    let universities;
    if (args.universityId) {
      const uni = await ctx.db.get(args.universityId);
      universities = uni ? [uni] : [];
    } else {
      // Get all active universities
      universities = await ctx.db
        .query('universities')
        .filter((q) => q.or(q.eq(q.field('status'), 'active'), q.eq(q.field('status'), 'trial')))
        .collect();
    }

    for (const university of universities) {
      // Get all active rules for this university
      const rules = await ctx.db
        .query('signal_rules')
        .withIndex('by_university_active', (q) =>
          q.eq('university_id', university._id).eq('is_active', true),
        )
        .collect();

      if (rules.length === 0) continue;

      // Get all students in this university
      const students = await ctx.db
        .query('users')
        .withIndex('by_university', (q) => q.eq('university_id', university._id))
        .filter((q) => q.eq(q.field('role'), 'student'))
        .collect();

      if (students.length === 0) continue;

      // BATCH PREFETCH: Fetch all data upfront to avoid O(rules × students × queries)
      // This reduces complexity to O(bulk_queries + rules × students × in_memory_operations)
      const studentIds = new Set(students.map((s) => s._id));
      const lookbackDays = 90; // Max lookback for any rule condition
      const lookbackTime = now - lookbackDays * 24 * 60 * 60 * 1000;

      // Batch fetch activity events for all students (within lookback period)
      const allActivityEvents = await ctx.db
        .query('activity_events')
        .withIndex('by_university', (q) => q.eq('university_id', university._id))
        .filter((q) => q.gte(q.field('occurred_at'), lookbackTime))
        .collect();

      // Batch fetch applications for all students
      const allApplications = await ctx.db
        .query('applications')
        .withIndex('by_university', (q) => q.eq('university_id', university._id))
        .collect();

      // Batch fetch follow-ups for all students (for appointment checking)
      const allFollowups = await ctx.db
        .query('follow_ups')
        .withIndex('by_university', (q) => q.eq('university_id', university._id))
        .filter((q) => q.gte(q.field('due_at'), lookbackTime))
        .collect();

      // Batch fetch recent signals for cooldown checking (max cooldown 90 days)
      const maxCooldownDays = Math.max(...rules.map((r) => r.cooldown_days ?? 0), 90);
      const cooldownLookback = now - maxCooldownDays * 24 * 60 * 60 * 1000;
      const ruleIds = new Set(rules.map((r) => r._id));
      const allRecentSignals = await ctx.db
        .query('signals')
        .withIndex('by_university', (q) => q.eq('university_id', university._id))
        .filter((q) => q.gte(q.field('triggered_at'), cooldownLookback))
        .collect();

      // Group data by user_id for efficient lookup
      const activityEventsByUser = new Map<string, typeof allActivityEvents>();
      for (const event of allActivityEvents) {
        if (studentIds.has(event.user_id)) {
          const existing = activityEventsByUser.get(event.user_id as string) || [];
          existing.push(event);
          activityEventsByUser.set(event.user_id as string, existing);
        }
      }

      const applicationsByUser = new Map<string, typeof allApplications>();
      for (const app of allApplications) {
        if (studentIds.has(app.user_id)) {
          const existing = applicationsByUser.get(app.user_id as string) || [];
          existing.push(app);
          applicationsByUser.set(app.user_id as string, existing);
        }
      }

      const followupsByUser = new Map<string, typeof allFollowups>();
      for (const followup of allFollowups) {
        if (studentIds.has(followup.user_id)) {
          const existing = followupsByUser.get(followup.user_id as string) || [];
          existing.push(followup);
          followupsByUser.set(followup.user_id as string, existing);
        }
      }

      // Group signals by rule_id + student_id for cooldown checking
      const signalsByRuleAndStudent = new Map<string, typeof allRecentSignals>();
      for (const signal of allRecentSignals) {
        if (signal.rule_id && ruleIds.has(signal.rule_id)) {
          const key = `${signal.rule_id}:${signal.student_id}`;
          const existing = signalsByRuleAndStudent.get(key) || [];
          existing.push(signal);
          signalsByRuleAndStudent.set(key, existing);
        }
      }

      // Prefetch engagement definitions once per university
      const engagementDefinitions = await ctx.db
        .query('engagement_definitions')
        .withIndex('by_university_active', (q) =>
          q.eq('university_id', university._id).eq('is_active', true),
        )
        .collect();
      const defaultDefinition =
        engagementDefinitions.find((d) => d.is_default) || engagementDefinitions[0] || null;

      // Bundle prefetched data for rule evaluation
      const prefetchedData = {
        activityEventsByUser,
        applicationsByUser,
        followupsByUser,
        engagementDefinition: defaultDefinition,
      };

      for (const rule of rules) {
        rulesEvaluated++;

        for (const student of students) {
          studentsChecked++;

          // Check if we should create a signal based on the rule condition
          const shouldTrigger = await evaluateRuleCondition(
            ctx,
            rule,
            student,
            now,
            prefetchedData,
          );

          if (shouldTrigger.triggered) {
            // Check cooldown using prefetched signals
            if (rule.cooldown_days) {
              const cooldownMs = rule.cooldown_days * 24 * 60 * 60 * 1000;
              const cooldownStart = now - cooldownMs;
              const key = `${rule._id}:${student._id}`;
              const recentSignals = signalsByRuleAndStudent.get(key) || [];
              const inCooldown = recentSignals.some((s) => s.triggered_at >= cooldownStart);

              if (inCooldown) {
                // Still in cooldown, skip
                continue;
              }
            }

            // Create the signal
            const signalId = await ctx.db.insert('signals', {
              university_id: university._id,
              student_id: student._id,
              rule_id: rule._id,
              source: 'rule',
              signal_type: rule.signal_type,
              title: rule.name,
              description: rule.description,
              priority: rule.priority,
              context_snapshot: shouldTrigger.context,
              status: 'active',
              triggered_at: now,
              created_at: now,
              updated_at: now,
            });

            // Schedule notification for advisors (only for urgent/high priority)
            if (rule.priority === 'urgent' || rule.priority === 'high') {
              await ctx.scheduler.runAfter(
                0,
                internal.signal_notifications.notifyAdvisorsForSignal,
                {
                  signalId,
                  studentId: student._id,
                  universityId: university._id,
                  priority: rule.priority,
                  signalTitle: rule.name,
                  signalDescription: rule.description,
                },
              );
            }

            signalsCreated++;
          }
        }
      }
    }

    console.log(
      `[Signal Cron] Evaluated ${rulesEvaluated} rules across ${studentsChecked} student checks. Created ${signalsCreated} new signals.`,
    );

    return { signalsCreated, rulesEvaluated, studentsChecked };
  },
});

// Type for prefetched data passed to evaluateRuleCondition
// Uses 'any' for complex document types to avoid coupling with full schema types
interface PrefetchedData {
  activityEventsByUser: Map<
    string,
    Array<{ event_type: string; occurred_at: number; entity_id?: string }>
  >;
  applicationsByUser: Map<
    string,
    Array<{
      _id: Id<'applications'>;
      stage?: string;
      status?: string;
      updated_at: number;
      company?: string;
      job_title?: string;
    }>
  >;
  followupsByUser: Map<string, Array<{ type?: string; due_at?: number }>>;
  engagementDefinition: { engaged_threshold: number; at_risk_threshold: number } | null;
}

/**
 * Evaluate a single rule condition against a student.
 * Returns { triggered: boolean, context?: object }
 *
 * OPTIMIZATION: Uses prefetched data to avoid O(rules × students × queries) complexity.
 * All data lookups are in-memory from pre-fetched Maps.
 */
async function evaluateRuleCondition(
  _ctx: QueryCtx, // Kept for backwards compatibility, but not used for data fetching
  rule: { condition: unknown },
  student: {
    _id: Id<'users'>;
    last_login_at?: number;
    university_id?: Id<'universities'> | null;
    engagement_status?: 'engaged' | 'moderate' | 'at_risk';
  },
  now: number,
  prefetchedData: PrefetchedData,
): Promise<{ triggered: boolean; context?: Record<string, unknown> }> {
  const condition = rule.condition as Record<string, unknown>;
  const conditionType = condition.type as string;

  // Helper to normalize stage/status for case-insensitive comparison
  // (legacy status is lowercase, stage is Title Case)
  const normalizeStage = (value?: string) => value?.toLowerCase();

  // Get prefetched data for this student (in-memory lookup)
  const studentIdStr = student._id as string;
  const studentEvents = prefetchedData.activityEventsByUser.get(studentIdStr) || [];
  const studentApplications = prefetchedData.applicationsByUser.get(studentIdStr) || [];
  const studentFollowups = prefetchedData.followupsByUser.get(studentIdStr) || [];

  switch (conditionType) {
    case 'inactivity': {
      const days = condition.days as number;
      const cutoffTime = now - days * 24 * 60 * 60 * 1000;

      // Check prefetched activity_events for recent activity (in-memory filter)
      const recentActivity = studentEvents.find((e) => e.occurred_at >= cutoffTime);

      if (!recentActivity) {
        // No activity events - fallback to last_login_at
        if (!student.last_login_at || student.last_login_at < cutoffTime) {
          const daysSinceActivity = student.last_login_at
            ? Math.floor((now - student.last_login_at) / (1000 * 60 * 60 * 24))
            : null;

          return {
            triggered: true,
            context: {
              daysSinceActivity,
              thresholdDays: days,
              lastActivityAt: student.last_login_at ?? null,
            },
          };
        }
      }

      return { triggered: false };
    }

    case 'application_stall': {
      const days = condition.days as number;
      const stage = condition.stage as string | undefined;
      const cutoffTime = now - days * 24 * 60 * 60 * 1000;

      // Use prefetched applications (in-memory filter)
      const applications = studentApplications.filter((app) => {
        const appStage = normalizeStage(app.stage ?? app.status);
        // Not in terminal state
        if (['accepted', 'rejected', 'withdrawn'].includes(appStage ?? '')) return false;
        // Stage hasn't changed recently
        return app.updated_at < cutoffTime;
      });

      // Filter by stage if specified (use stage with fallback to legacy status)
      const stageNorm = normalizeStage(stage);
      const stalledApps = stage
        ? applications.filter((app) => normalizeStage(app.stage ?? app.status) === stageNorm)
        : applications;

      if (stalledApps.length > 0) {
        const oldestStall = stalledApps.reduce((oldest, app) =>
          app.updated_at < oldest.updated_at ? app : oldest,
        );

        return {
          triggered: true,
          context: {
            stalledApplications: stalledApps.length,
            stalledStage: stage ?? 'any',
            oldestStallDays: Math.floor((now - oldestStall.updated_at) / (1000 * 60 * 60 * 24)),
            thresholdDays: days,
          },
        };
      }

      return { triggered: false };
    }

    case 'engagement_drop': {
      // For engagement drop, we compare previous (cached) and current engagement levels
      // Only trigger on actual downward transitions to avoid spamming advisors

      const fromLevel = condition.from as string;
      const toLevel = condition.to as string;
      const previousLevel = student.engagement_status;

      // Use prefetched engagement definition
      if (!student.university_id) return { triggered: false };
      const definition = prefetchedData.engagementDefinition;
      if (!definition) return { triggered: false };

      // Calculate current engagement score based on prefetched activity (in-memory filter)
      const fourteenDaysAgo = now - 14 * 24 * 60 * 60 * 1000;
      const recentEvents = studentEvents.filter((e) => e.occurred_at >= fourteenDaysAgo);

      // Simple scoring: count activity events in last 14 days
      const activityScore = Math.min(100, recentEvents.length * 10);

      let currentLevel: string;
      if (activityScore >= definition.engaged_threshold) {
        currentLevel = 'engaged';
      } else if (activityScore <= definition.at_risk_threshold) {
        currentLevel = 'at_risk';
      } else {
        currentLevel = 'moderate';
      }

      // levelOrder: index 0 = best (engaged), index 2 = worst (at_risk)
      const levelOrder = ['engaged', 'moderate', 'at_risk'];
      const currentIdx = levelOrder.indexOf(currentLevel);
      const toIdx = levelOrder.indexOf(toLevel);
      const fromIdx = levelOrder.indexOf(fromLevel);
      const prevIdx = previousLevel ? levelOrder.indexOf(previousLevel) : -1;

      // Only trigger on actual downward transition:
      // - Must have a valid previous level
      // - Previous level must be at or better than "from" level
      // - Current level must be at or worse than "to" level
      // - Current level must be worse than previous level (actual drop)
      if (
        prevIdx >= 0 &&
        fromIdx >= 0 &&
        toIdx >= 0 &&
        currentIdx > prevIdx && // Actually dropped
        prevIdx <= fromIdx && // Was at or better than "from"
        currentIdx >= toIdx // Now at or worse than "to"
      ) {
        return {
          triggered: true,
          context: {
            currentLevel,
            previousLevel,
            targetFromLevel: fromLevel,
            targetToLevel: toLevel,
            activityScore,
            recentActivityCount: recentEvents.length,
          },
        };
      }

      return { triggered: false };
    }

    case 'no_progress': {
      // Check application outcomes - many rejections, no offers (use prefetched data)
      const rejectionsMin = (condition.rejections_min as number) ?? 5;
      const offersMax = (condition.offers as number) ?? 0;

      const applications = studentApplications;

      const rejections = applications.filter(
        (app) => normalizeStage(app.stage ?? app.status) === 'rejected',
      ).length;
      const offers = applications.filter((app) =>
        ['offer', 'accepted'].includes(normalizeStage(app.stage ?? app.status) ?? ''),
      ).length;

      if (rejections >= rejectionsMin && offers <= offersMax) {
        return {
          triggered: true,
          context: {
            rejectionCount: rejections,
            offerCount: offers,
            rejectionsThreshold: rejectionsMin,
            totalApplications: applications.length,
          },
        };
      }

      return { triggered: false };
    }

    case 'custom': {
      // Custom conditions are not auto-evaluated for now
      // They require manual signal creation or specialized handling
      return { triggered: false };
    }

    // ========================================================================
    // NEW SIGNAL CONDITIONS FOR ENGAGEMENT-TO-MOMENTUM ENGINE
    // ========================================================================

    case 'stalled': {
      // STALLED: No qualifying activity in X days
      // Uses engagement definition's qualifying event types
      const days = (condition.days as number) ?? 14;
      const cutoffTime = now - days * 24 * 60 * 60 * 1000;

      // Get qualifying event types (from condition or default list)
      const qualifyingEventTypes = (condition.qualifying_event_types as string[]) ?? [
        'login',
        'application_created',
        'application_updated',
        'application_stage_changed',
        'resume_created',
        'resume_updated',
        'goal_created',
        'goal_updated',
        'goal_completed',
        'coach_conversation_started',
        'coach_message_sent',
      ];

      // Check for qualifying activity in the period (use prefetched data, in-memory filter)
      const recentEvents = studentEvents.filter((e) => e.occurred_at >= cutoffTime);

      // Filter to only qualifying events
      const qualifyingEvents = recentEvents.filter((event) =>
        qualifyingEventTypes.includes(event.event_type),
      );

      if (qualifyingEvents.length === 0) {
        // Find the last qualifying event from prefetched data (in-memory)
        // Events are within lookback period, so find the most recent qualifying one
        const qualifyingFromPrefetch = studentEvents
          .filter((e) => qualifyingEventTypes.includes(e.event_type))
          .sort((a, b) => b.occurred_at - a.occurred_at);
        const lastQualifying = qualifyingFromPrefetch[0];

        const lastActivityAt = lastQualifying?.occurred_at ?? student.last_login_at ?? null;
        const daysSinceActivity = lastActivityAt
          ? Math.floor((now - lastActivityAt) / (1000 * 60 * 60 * 24))
          : null;

        return {
          triggered: true,
          context: {
            condition_type: 'stalled',
            days_since_activity: daysSinceActivity,
            threshold_days: days,
            last_activity_at: lastActivityAt,
            qualifying_event_types: qualifyingEventTypes,
          },
        };
      }

      return { triggered: false };
    }

    case 'high_intent_low_conversion': {
      // HIGH_INTENT_LOW_CONVERSION: N applications in period + no appointment/meeting
      const applicationsThreshold = (condition.applications_threshold as number) ?? 3;
      const applicationPeriodDays = (condition.application_period_days as number) ?? 14;
      const appointmentDays = (condition.appointment_days as number) ?? 30;

      const applicationCutoff = now - applicationPeriodDays * 24 * 60 * 60 * 1000;
      const appointmentCutoff = now - appointmentDays * 24 * 60 * 60 * 1000;

      // Count applications created in period (use prefetched data, in-memory filter)
      const applicationEvents = studentEvents.filter(
        (e) => e.occurred_at >= applicationCutoff && e.event_type === 'application_created',
      );

      const applicationCount = applicationEvents.length;

      if (applicationCount >= applicationsThreshold) {
        // Check for appointment/meeting events (in-memory filter)
        const appointmentEventTypes = [
          'appointment_scheduled',
          'appointment_completed',
          'session_scheduled',
          'session_completed',
          'meeting_scheduled',
          'meeting_completed',
          'advisor_session',
        ];

        const hasAppointment = studentEvents.some(
          (e) => e.occurred_at >= appointmentCutoff && appointmentEventTypes.includes(e.event_type),
        );

        // Also check prefetched follow_ups for scheduled sessions (in-memory filter)
        const recentFollowup = studentFollowups.find(
          (f) => f.due_at !== undefined && f.due_at >= appointmentCutoff && f.type === 'meeting',
        );

        if (!hasAppointment && !recentFollowup) {
          return {
            triggered: true,
            context: {
              condition_type: 'high_intent_low_conversion',
              application_count: applicationCount,
              applications_threshold: applicationsThreshold,
              application_period_days: applicationPeriodDays,
              appointment_days: appointmentDays,
              has_recent_appointment: false,
            },
          };
        }
      }

      return { triggered: false };
    }

    case 'stage_stuck': {
      // STAGE_STUCK: Application stuck in a specific stage for Y days
      const targetStage = condition.stage as string; // e.g., 'Interview', 'Applied', or 'any'
      const days = (condition.days as number) ?? 14;
      const cutoffTime = now - days * 24 * 60 * 60 * 1000;

      // Get applications for this student (use prefetched data, in-memory filter)
      const applications = studentApplications.filter((app) => {
        const appStage = normalizeStage(app.stage ?? app.status);
        // Not in terminal state
        return !['accepted', 'rejected', 'withdrawn'].includes(appStage ?? '');
      });

      // Filter by specific stage if not 'any' (use stage with fallback to legacy status)
      const targetStageNorm = normalizeStage(targetStage);
      const stageFiltered =
        targetStage === 'any'
          ? applications
          : applications.filter(
              (app) => normalizeStage(app.stage ?? app.status) === targetStageNorm,
            );

      // Check which applications haven't had a stage change recently (in-memory)
      const stuckApps = [];
      for (const app of stageFiltered) {
        // Check prefetched activity_events for recent stage changes
        const recentStageChange = studentEvents.find(
          (e) =>
            e.occurred_at >= cutoffTime &&
            e.event_type === 'application_stage_changed' &&
            e.entity_id === app._id.toString(),
        );

        // If no recent stage change and app was last updated before cutoff
        if (!recentStageChange && app.updated_at < cutoffTime) {
          const daysSinceUpdate = Math.floor((now - app.updated_at) / (1000 * 60 * 60 * 24));
          stuckApps.push({
            application_id: app._id,
            company: app.company ?? 'Unknown',
            position: app.job_title ?? 'Unknown',
            stage: app.stage ?? app.status,
            days_stuck: daysSinceUpdate,
          });
        }
      }

      if (stuckApps.length > 0) {
        // Find the application stuck the longest
        const longestStuck = stuckApps.reduce((longest, app) =>
          app.days_stuck > longest.days_stuck ? app : longest,
        );

        return {
          triggered: true,
          context: {
            condition_type: 'stage_stuck',
            stuck_applications: stuckApps.length,
            target_stage: targetStage,
            threshold_days: days,
            longest_stuck: longestStuck,
            all_stuck_apps: stuckApps.slice(0, 5), // Limit to 5 for context
          },
        };
      }

      return { triggered: false };
    }

    default:
      return { triggered: false };
  }
}

// ============================================================================
// SIGNAL EXPLANATION GENERATOR
// ============================================================================

/**
 * Generate a plain-English explanation for a signal.
 * Used for displaying signals in the student timeline.
 */
export function generateSignalExplanation(
  conditionType: string,
  context: Record<string, unknown>,
): string {
  switch (conditionType) {
    case 'stalled': {
      const days = context.days_since_activity as number | null;
      const threshold = context.threshold_days as number;
      if (days !== null) {
        return `No activity in ${days} days. Has been inactive for longer than the ${threshold}-day threshold.`;
      }
      return `No recorded activity. Student may need outreach.`;
    }

    case 'high_intent_low_conversion': {
      const appCount = context.application_count as number;
      const appointmentDays = context.appointment_days as number;
      return `${appCount} applications submitted but no advising appointment scheduled in ${appointmentDays} days. May need guidance on next steps.`;
    }

    case 'stage_stuck': {
      const longestStuck = context.longest_stuck as
        | {
            company: string;
            stage: string;
            days_stuck: number;
          }
        | undefined;
      const stuckCount = context.stuck_applications as number;

      if (longestStuck) {
        if (stuckCount > 1) {
          return `${stuckCount} applications stuck, including ${longestStuck.company} in "${longestStuck.stage}" stage for ${longestStuck.days_stuck} days.`;
        }
        return `Application at ${longestStuck.company} stuck in "${longestStuck.stage}" stage for ${longestStuck.days_stuck} days.`;
      }
      return `Application stuck in same stage for extended period.`;
    }

    case 'inactivity': {
      const days = context.daysSinceActivity as number | null;
      const threshold = context.thresholdDays as number;
      if (days !== null) {
        return `Last activity was ${days} days ago, exceeding the ${threshold}-day threshold.`;
      }
      return `No recent activity recorded.`;
    }

    case 'application_stall': {
      const count = context.stalledApplications as number;
      const stage = context.stalledStage as string;
      const oldest = context.oldestStallDays as number;
      if (stage !== 'any') {
        return `${count} application(s) stuck in "${stage}" stage for ${oldest}+ days.`;
      }
      return `${count} application(s) haven't progressed in ${oldest}+ days.`;
    }

    case 'engagement_drop': {
      const current = context.currentLevel as string;
      const previous = context.previousLevel as string | undefined;
      const from = previous || (context.targetFromLevel as string);
      return `Engagement level dropped from ${from} to ${current}. May need check-in.`;
    }

    case 'no_progress': {
      const rejections = context.rejectionCount as number;
      const offers = context.offerCount as number;
      const total = context.totalApplications as number;
      return `${rejections} rejections out of ${total} applications with ${offers} offer(s). May need application strategy review.`;
    }

    default:
      return 'Action may be needed. Please review student profile.';
  }
}

/**
 * Get the condition type from a signal's context or rule.
 */
export function getConditionTypeFromSignal(signal: {
  context_snapshot?: Record<string, unknown>;
  rule_id?: Id<'signal_rules'>;
}): string {
  if (signal.context_snapshot?.condition_type) {
    return signal.context_snapshot.condition_type as string;
  }
  // Fallback - try to infer from context keys
  if (signal.context_snapshot?.days_since_activity !== undefined) return 'stalled';
  if (signal.context_snapshot?.application_count !== undefined) return 'high_intent_low_conversion';
  if (signal.context_snapshot?.stuck_applications !== undefined) return 'stage_stuck';
  if (signal.context_snapshot?.daysSinceActivity !== undefined) return 'inactivity';
  if (signal.context_snapshot?.stalledApplications !== undefined) return 'application_stall';
  if (signal.context_snapshot?.currentLevel !== undefined) return 'engagement_drop';
  if (signal.context_snapshot?.rejectionCount !== undefined) return 'no_progress';

  return 'unknown';
}

/**
 * Archive and clean up old signals.
 * Two-tier retention policy to preserve analytics/audit history:
 * 1. Archive: resolved/dismissed signals older than archiveAfterDays (default 90) → archived status
 * 2. Purge: archived signals older than purgeAfterDays (default 365) → hard delete
 *
 * Called by cron job daily.
 */
export const cleanupOldSignals = internalMutation({
  args: {
    archiveAfterDays: v.optional(v.number()), // Archive resolved/dismissed after N days (default 90)
    purgeAfterDays: v.optional(v.number()), // Hard delete archived after N days (default 365)
  },
  handler: async (ctx, args) => {
    const now = Date.now();
    const archiveAfterDays = args.archiveAfterDays ?? 90;
    const purgeAfterDays = args.purgeAfterDays ?? 365;
    const archiveCutoff = now - archiveAfterDays * 24 * 60 * 60 * 1000;
    const purgeCutoff = now - purgeAfterDays * 24 * 60 * 60 * 1000;

    let archived = 0;
    let purged = 0;
    const batchSize = 500;

    // PHASE 1: Archive old resolved/dismissed signals (soft-delete)
    while (true) {
      const signalsToArchive = await ctx.db
        .query('signals')
        .filter((q) =>
          q.and(
            q.or(q.eq(q.field('status'), 'resolved'), q.eq(q.field('status'), 'dismissed')),
            q.lt(q.field('updated_at'), archiveCutoff),
          ),
        )
        .take(batchSize);

      if (signalsToArchive.length === 0) break;

      for (const signal of signalsToArchive) {
        await ctx.db.patch(signal._id, {
          status: 'archived',
          archived_at: now,
          updated_at: now,
        });
        archived++;
      }

      // Safety limit
      if (archived >= 5000) break;
    }

    // PHASE 2: Purge very old archived signals (hard delete after 365 days)
    while (true) {
      const signalsToPurge = await ctx.db
        .query('signals')
        .filter((q) =>
          q.and(q.eq(q.field('status'), 'archived'), q.lt(q.field('archived_at'), purgeCutoff)),
        )
        .take(batchSize);

      if (signalsToPurge.length === 0) break;

      for (const signal of signalsToPurge) {
        await ctx.db.delete(signal._id);
        purged++;
      }

      // Safety limit
      if (purged >= 5000) break;
    }

    console.log(
      `[Signal Cron] Archived ${archived} old signals, purged ${purged} expired archived signals`,
    );
    return { archived, purged };
  },
});

// ============================================================================
// ANALYTICS QUERIES
// ============================================================================

/**
 * Get signal analytics for a university.
 * Provides aggregate metrics for the analytics dashboard.
 */
export const getSignalAnalytics = query({
  args: {
    universityId: v.id('universities'),
    dateRange: v.optional(
      v.object({
        start: v.number(),
        end: v.number(),
      }),
    ),
  },
  handler: async (ctx, args) => {
    const sessionCtx = await getCurrentUser(ctx);

    // Authorization check
    if (sessionCtx.role !== 'super_admin') {
      const universityId = requireTenant(sessionCtx);
      if (universityId !== args.universityId) {
        throw new Error('Unauthorized: Cannot access analytics for another university');
      }
    }

    const now = Date.now();
    const thirtyDaysAgo = now - 30 * 24 * 60 * 60 * 1000;
    const start = args.dateRange?.start ?? thirtyDaysAgo;
    const end = args.dateRange?.end ?? now;

    // Get all signals for this university
    const allSignals = await ctx.db
      .query('signals')
      .withIndex('by_university', (q) => q.eq('university_id', args.universityId))
      .collect();

    // Filter by date range
    const signalsInRange = allSignals.filter((s) => s.created_at >= start && s.created_at <= end);

    // Current status breakdown
    const statusCounts = {
      active: allSignals.filter((s) => s.status === 'active').length,
      snoozed: allSignals.filter((s) => s.status === 'snoozed').length,
      resolved: allSignals.filter((s) => s.status === 'resolved').length,
      dismissed: allSignals.filter((s) => s.status === 'dismissed').length,
    };

    // Priority breakdown (active only)
    const activeSignals = allSignals.filter((s) => s.status === 'active');
    const priorityCounts = {
      urgent: activeSignals.filter((s) => s.priority === 'urgent').length,
      high: activeSignals.filter((s) => s.priority === 'high').length,
      medium: activeSignals.filter((s) => s.priority === 'medium').length,
      low: activeSignals.filter((s) => s.priority === 'low').length,
    };

    // Signal type breakdown (all signals in range)
    const typeCounts = {
      needs_outreach: signalsInRange.filter((s) => s.signal_type === 'needs_outreach').length,
      application_support: signalsInRange.filter((s) => s.signal_type === 'application_support')
        .length,
      document_review: signalsInRange.filter((s) => s.signal_type === 'document_review').length,
      milestone_check: signalsInRange.filter((s) => s.signal_type === 'milestone_check').length,
      custom: signalsInRange.filter((s) => s.signal_type === 'custom').length,
    };

    // Source breakdown
    const sourceCounts = {
      rule: signalsInRange.filter((s) => s.source === 'rule').length,
      manual: signalsInRange.filter((s) => s.source === 'manual').length,
      system: signalsInRange.filter((s) => s.source === 'system').length,
    };

    // Resolution type breakdown (resolved signals only)
    const resolvedSignals = signalsInRange.filter((s) => s.status === 'resolved');
    const resolutionCounts = {
      action_taken: resolvedSignals.filter((s) => s.resolution_type === 'action_taken').length,
      no_action_needed: resolvedSignals.filter((s) => s.resolution_type === 'no_action_needed')
        .length,
      dismissed: resolvedSignals.filter((s) => s.resolution_type === 'dismissed').length,
      auto_resolved: resolvedSignals.filter((s) => s.resolution_type === 'auto_resolved').length,
    };

    // Calculate average resolution time
    const resolvedWithTimes = resolvedSignals.filter((s) => s.resolved_at && s.triggered_at);
    let avgResolutionTimeHours: number | null = null;
    if (resolvedWithTimes.length > 0) {
      const totalMs = resolvedWithTimes.reduce(
        (sum, s) => sum + ((s.resolved_at || 0) - s.triggered_at),
        0,
      );
      avgResolutionTimeHours = Math.round(totalMs / resolvedWithTimes.length / (1000 * 60 * 60));
    }

    // Daily signal creation trend (last 30 days)
    const dailyTrend: { date: string; created: number; resolved: number }[] = [];
    for (let i = 29; i >= 0; i--) {
      const dayStart = now - (i + 1) * 24 * 60 * 60 * 1000;
      const dayEnd = now - i * 24 * 60 * 60 * 1000;
      const date = new Date(dayEnd).toISOString().split('T')[0];

      const created = allSignals.filter(
        (s) => s.created_at >= dayStart && s.created_at < dayEnd,
      ).length;
      const resolved = allSignals.filter(
        (s) =>
          s.status === 'resolved' &&
          s.resolved_at &&
          s.resolved_at >= dayStart &&
          s.resolved_at < dayEnd,
      ).length;

      dailyTrend.push({ date, created, resolved });
    }

    // Top students with most active signals
    const studentSignalCounts = new Map<string, number>();
    for (const s of activeSignals) {
      const count = studentSignalCounts.get(s.student_id) ?? 0;
      studentSignalCounts.set(s.student_id, count + 1);
    }
    const topStudentIds = Array.from(studentSignalCounts.entries())
      .sort((a, b) => b[1] - a[1])
      .slice(0, 10);

    const topStudents: Array<{
      studentId: string;
      name: string;
      email: string;
      activeSignals: number;
    }> = [];
    for (const [studentId, count] of topStudentIds) {
      const user = await ctx.db.get(studentId as Id<'users'>);
      if (user) {
        topStudents.push({
          studentId,
          name: user.name || 'Unknown',
          email: user.email || '',
          activeSignals: count,
        });
      }
    }

    // Top rules by signal count
    const ruleSignalCounts = new Map<string, number>();
    for (const s of signalsInRange) {
      if (s.rule_id) {
        const count = ruleSignalCounts.get(s.rule_id) ?? 0;
        ruleSignalCounts.set(s.rule_id, count + 1);
      }
    }
    const topRuleIds = Array.from(ruleSignalCounts.entries())
      .sort((a, b) => b[1] - a[1])
      .slice(0, 5);

    const topRules: Array<{
      ruleId: string;
      name: string;
      signalCount: number;
    }> = [];
    for (const [ruleId, count] of topRuleIds) {
      const rule = await ctx.db.get(ruleId as Id<'signal_rules'>);
      if (rule) {
        topRules.push({
          ruleId,
          name: rule.name,
          signalCount: count,
        });
      }
    }

    return {
      summary: {
        totalSignals: allSignals.length,
        activeSignals: statusCounts.active,
        signalsInPeriod: signalsInRange.length,
        resolvedInPeriod: resolvedSignals.length,
        avgResolutionTimeHours,
      },
      statusCounts,
      priorityCounts,
      typeCounts,
      sourceCounts,
      resolutionCounts,
      dailyTrend,
      topStudents,
      topRules,
    };
  },
});

/**
 * Get signal rule effectiveness metrics.
 * Shows how each rule is performing.
 */
export const getRuleEffectiveness = query({
  args: {
    universityId: v.id('universities'),
  },
  handler: async (ctx, args) => {
    const sessionCtx = await getCurrentUser(ctx);

    // Authorization check
    if (sessionCtx.role !== 'super_admin') {
      const universityId = requireTenant(sessionCtx);
      if (universityId !== args.universityId) {
        throw new Error('Unauthorized: Cannot access analytics for another university');
      }
    }

    // Get all rules for this university
    const rules = await ctx.db
      .query('signal_rules')
      .withIndex('by_university', (q) => q.eq('university_id', args.universityId))
      .collect();

    // Get all signals for this university
    const allSignals = await ctx.db
      .query('signals')
      .withIndex('by_university', (q) => q.eq('university_id', args.universityId))
      .collect();

    const ruleMetrics: Array<{
      ruleId: string;
      name: string;
      isActive: boolean;
      totalSignals: number;
      activeSignals: number;
      resolvedWithAction: number;
      resolvedNoAction: number;
      dismissedCount: number;
      avgResolutionHours: number | null;
      effectivenessRate: number;
    }> = [];

    for (const rule of rules) {
      const ruleSignals = allSignals.filter((s) => s.rule_id === rule._id);
      const activeCount = ruleSignals.filter((s) => s.status === 'active').length;
      const resolvedWithAction = ruleSignals.filter(
        (s) => s.status === 'resolved' && s.resolution_type === 'action_taken',
      ).length;
      const resolvedNoAction = ruleSignals.filter(
        (s) => s.status === 'resolved' && s.resolution_type === 'no_action_needed',
      ).length;
      const dismissedCount = ruleSignals.filter((s) => s.status === 'dismissed').length;

      const resolvedWithTimes = ruleSignals.filter(
        (s) => s.status === 'resolved' && s.resolved_at && s.triggered_at,
      );
      let avgResolutionHours: number | null = null;
      if (resolvedWithTimes.length > 0) {
        const totalMs = resolvedWithTimes.reduce(
          (sum, s) => sum + ((s.resolved_at || 0) - s.triggered_at),
          0,
        );
        avgResolutionHours = Math.round(totalMs / resolvedWithTimes.length / (1000 * 60 * 60));
      }

      // Effectiveness = action taken / (action taken + no action needed + dismissed)
      const totalResolved = resolvedWithAction + resolvedNoAction + dismissedCount;
      const effectivenessRate =
        totalResolved > 0 ? Math.round((resolvedWithAction / totalResolved) * 100) : 0;

      ruleMetrics.push({
        ruleId: rule._id,
        name: rule.name,
        isActive: rule.is_active,
        totalSignals: ruleSignals.length,
        activeSignals: activeCount,
        resolvedWithAction,
        resolvedNoAction,
        dismissedCount,
        avgResolutionHours,
        effectivenessRate,
      });
    }

    // Sort by total signals descending
    ruleMetrics.sort((a, b) => b.totalSignals - a.totalSignals);

    return ruleMetrics;
  },
});
